DROP TRIGGER IF EXISTS mindsurf.WHEN_DELETE_IDEA;

DELIMITER //

CREATE TRIGGER mindsurf.WHEN_DELETE_IDEA AFTER DELETE ON mindsurf.IDEA

FOR EACH ROW

BEGIN

UPDATE mindsurf.TAG SET ideas=ideas-1 WHERE id=OLD.tag_id;

END //

DELIMITER ;